import type { Metadata } from "next";
import { z } from "zod";

/*
 * Shared page metadata (title, description, canonical URL, Open Graph, Twitter card).
 *
 * Next.js merges `metadata` from layouts and pages *shallowly*: a page that sets `openGraph`
 * replaces the layout's whole `openGraph` object. `pageMetadata()` therefore rebuilds the full
 * object for every page, so `siteName`, `locale` and `type` are never lost.
 */

export const SITE_NAME = "Paws & Paths";
export const SITE_TAGLINE = "Trusted local dog walkers";
export const SITE_DESCRIPTION =
  "Paws & Paths connects dog owners with trusted local walkers. Store your dog's care details, find a walker nearby, and book walks.";

/** Search snippets cut off around 160 characters. */
const DESCRIPTION_MAX = 160;

/**
 * Public origin used for absolute URLs in canonical links, Open Graph tags, robots.txt and the
 * sitemap. Not a secret. Falls back to the dev server when unset or invalid, so a typo can't
 * break the build.
 */
export const SITE_URL = z
  .url({ protocol: /^https?$/ })
  .catch("http://localhost:3000")
  .parse(process.env.SITE_URL ?? "http://localhost:3000");

/** Trims to a search-snippet-sized description on a word boundary. */
export function toDescription(text: string): string {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= DESCRIPTION_MAX) return clean;
  const cut = clean.slice(0, DESCRIPTION_MAX - 1);
  return `${cut.slice(0, cut.lastIndexOf(" ") > 0 ? cut.lastIndexOf(" ") : cut.length)}…`;
}

/**
 * Default share image, generated by `app/opengraph-image.tsx`. Set explicitly because a page's own
 * `openGraph` object replaces the layout's, which would otherwise drop the file-based image.
 */
const DEFAULT_SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: `${SITE_NAME}: ${SITE_TAGLINE}` };

/** Site-wide defaults for the root layout. No canonical URL or `og:url`: those belong to each page. */
export const SITE_DEFAULT_METADATA: Metadata = {
  description: SITE_DESCRIPTION,
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en_US",
    title: `${SITE_NAME}: ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: [DEFAULT_SHARE_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME}: ${SITE_TAGLINE}`,
    description: SITE_DESCRIPTION,
    images: [DEFAULT_SHARE_IMAGE],
  },
};

/** Signed-in or form-only pages: keep them out of search results, but let crawlers follow links. */
export const PRIVATE_PAGE_ROBOTS: Metadata["robots"] = { index: false, follow: true };

interface PageMetadataInput {
  /** Short page title. The root layout's template adds " · Paws & Paths". */
  title: string;
  description: string;
  /** Site-relative path, e.g. `/walkers`. Used for the canonical URL and `og:url`. */
  path: string;
  /** `true` for pages that should not appear in search results. */
  private?: boolean;
  openGraphType?: "website" | "profile";
  /** Optional https image (already validated with `httpsUrlSchema`). Defaults to the generated site image. */
  image?: { url: string; alt: string };
}

/** Metadata for one page, with consistent Open Graph and Twitter tags. */
export function pageMetadata({
  title,
  description,
  path,
  private: isPrivate = false,
  openGraphType = "website",
  image,
}: PageMetadataInput): Metadata {
  const shareTitle = `${title} · ${SITE_NAME}`;
  const shareDescription = toDescription(description);
  const shareImage = image ?? DEFAULT_SHARE_IMAGE;
  return {
    title,
    description: shareDescription,
    alternates: { canonical: path },
    ...(isPrivate ? { robots: PRIVATE_PAGE_ROBOTS } : {}),
    openGraph: {
      type: openGraphType,
      siteName: SITE_NAME,
      locale: "en_US",
      url: path,
      title: shareTitle,
      description: shareDescription,
      images: [shareImage],
    },
    twitter: {
      card: image ? "summary" : "summary_large_image",
      title: shareTitle,
      description: shareDescription,
      images: [shareImage],
    },
  };
}
